version: "3.9"
services:
  nextapp:
    container_name: nextapp
    build: .
    ports:
      - "3000:3000"

  chromadb:
    container_name: chromadb
    image: chromadb/chroma:0.6.2
    volumes:
      - ./chroma:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=TRUE
    ports:
      - "8000:8000"
